services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - weather_source 
    networks:
      - appnet

  weather_source:
    build:
      context: ./weather_source_service
      dockerfile: Dockerfile
    container_name: weather-source-service 
    ports:
      - "8000:8000"
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - appnet

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    user: root
    ports:
      - "9092:9092"
      - "29092:29092"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9092"]
      interval: 5s
      timeout: 5s
      retries: 20

    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller

      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,INTERNAL://kafka:29092

      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093

      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_share.coordinator.state.topic.min.isr=1
      - KAFKA_CFG_transaction.state.log.min.isr=1
      - KAFKA_CFG_offsets.topic.num.partitions=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL

    networks:
      - appnet

  weather_ingestion_worker:
    build:
      context: ./weather_ingestion_worker
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_healthy
      weather_source:
        condition: service_started
    networks:
      - appnet

  weather:
    build:
      context: ./weather_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_URL_PROD=mongodb://mongo:27017/weather
      # SET YOUR OPENAI_API_KEY: https://platform.openai.com/api-keys
      - OPENAI_API_KEY=
    depends_on:
      kafka:
        condition: service_healthy
      mongo:
        condition: service_started
    networks:
      - appnet
  redis:
    image: redis:alpine3.22
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - appnet
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

